### ISSUE TITLE
httk not working with Python3.10

### ISSUE THREAD

**Issue by lkasillas** [httk/httk#52]
When using python3.10 I get the following error:
AttributeError: module 'collections' has no attribute 'Iterable'

With python3.8 works fine

**Comment by rartino** [comment]
Apparently `collections.Iterable` was deprecated and removed, and is replaced by `collections.abc.Iterable`.

This should be easy enough to fix in httk; here is a stack overflow post suggesting a backwards-compatible way: https://stackoverflow.com/questions/53978542/how-to-use-collections-abc-from-both-python-3-8-and-python-2-7/53978543#53978543

**Comment by rartino** [comment]
Thanks for reporting. This is now fixed in the current devel repo; tests run for py2.7, py3.8 - py3.12.
